version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: blog_cbv
      POSTGRES_USER: blog
      POSTGRES_PASSWORD: xxxxxx
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webnet

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - webnet

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=blog_cbv.settings
      - DEBUG=True
      - SECRET_KEY=django-insecure-4bo7!+t80(5m44+_^y3b+k1jwfincw_!!h0=qkn+qf&-6ek!3%
      - DB_NAME=blog_cbv
      - DB_USER=blog
      - DB_PASSWORD=xxxxxx
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      - webnet

volumes:
  postgres_data:
  static_volume:

networks:
  webnet:
